version: '3'

services:
  eurekaService1:
    image: microservice/eureka-service
    container_name: eurekaService1
    build:
      context: ./eureka-service
    ports:
      - "8761:8761"
    environment:
      - "EUREKA_INSTANCE_HOSTNAME=eureka-peer1"
      - "EUREKA_SERVER_LIST=http://eureka-peer2:8761/eureka,http://eureka-peer3:8761/eureka"
#      - "EUREKA_SPRING_PROFILES_ACTIVE=eureka-clustered"
    networks:
      eureka_net:
        aliases:
          - eureka-peer1
  eurekaService2:
    image: microservice/eureka-service
    container_name: eurekaService2
    build:
      context: ./eureka-service
    ports:
      - "8762:8761"
    environment:
      - "EUREKA_INSTANCE_HOSTNAME=eureka-peer2"
      - "EUREKA_SERVER_LIST=http://eureka-peer1:8761/eureka,http://eureka-peer3:8761/eureka"
#      - "EUREKA_SPRING_PROFILES_ACTIVE=eureka-clustered"
    networks:
      eureka_net:
        aliases:
          - eureka-peer2
  eurekaService3:
    image: microservice/eureka-service
    container_name: eurekaService3
    build:
      context: ./eureka-service
    ports:
      - "8763:8761"
    environment:
      - "EUREKA_INSTANCE_HOSTNAME=eureka-peer3"
      - "EUREKA_SERVER_LIST=http://eureka-peer1:8761/eureka,http://eureka-peer2:8761/eureka"
#      - "EUREKA_SPRING_PROFILES_ACTIVE=eureka-clustered"
    networks:
      eureka_net:
        aliases:
          - eureka-peer3
  gatewayService:
    image: microservice/gateway-service
    container_name: gatewayService
    build:
      context: ./gateway-service
    ports:
      - "8082:8082"
    networks:
      - eureka_net
    environment:
#      - "EUREKA_SERVER_LIST=http://eureka-peer1:8761/eureka,http://eureka-peer2:8762/eureka,http://eureka-peer3:8763/eureka"
networks:
  eureka_net:
    driver: bridge
  elk:
    driver: bridge
