server:
  port: 8082
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled:  true #default:false, uses serviceId to create a route ex: user-service uri:/user/list => localhost:port/USER-SERVER/user/list
      #          lower-case-service-id:  true # services register to eureka default are uppercase name  ex:FLASHSALE-SERVICE
eureka:
  client:
    register-with-eureka: true #default: true
    service-url:
      defaultZone: ${EUREKA_SERVER_LIST:http://eureka-peer1:8761/eureka/,http://eureka-peer2:8762/eureka/,http://eureka-peer3:8763/eureka/}
logging:
  level:
    org.springframework.cloud.gateway: debug

ignore:
  # 此屬性用來設定不生成該服務的swagger文件
  swagger-providers:
    #- "FLASHSALE-SERVICE"